// Code generated by operations-gen. DO NOT EDIT.

package burn_mint_erc677

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
	gobindings "github.com/smartcontractkit/chainlink-evm/gethwrappers/shared/generated/initial/burn_mint_erc677"
)

var ContractType cldf_deployment.ContractType = "BurnMintERC677"
var Version = semver.MustParse("1.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

func NewReadOwner(c gobindings.BurnMintERC677Interface) *cld_ops.Operation[contract.FunctionInput[struct{}], common.Address, cldf_evm.Chain] {
	return contract.NewRead(contract.ReadParams[struct{}, common.Address, gobindings.BurnMintERC677Interface]{
		Name:         "burn-mint-erc677:owner",
		Version:      Version,
		Description:  "Calls owner on the contract",
		ContractType: ContractType,
		Contract:     c,
		CallContract: func(c gobindings.BurnMintERC677Interface, opts *bind.CallOpts, args struct{}) (common.Address, error) {
			return c.Owner(opts)
		},
	})
}

func NewWriteTransferOwnership(c gobindings.BurnMintERC677Interface) *cld_ops.Operation[contract.FunctionInput[common.Address], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[common.Address, gobindings.BurnMintERC677Interface]{
		Name:         "burn-mint-erc677:transfer-ownership",
		Version:      Version,
		Description:  "Calls transferOwnership on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.BurnMintERC677MetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.BurnMintERC677Interface, opts *bind.CallOpts, caller common.Address, args common.Address) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.BurnMintERC677Interface,
			opts *bind.TransactOpts,
			args common.Address,
		) (*types.Transaction, error) {
			return c.TransferOwnership(opts, args)
		},
	})
}

func NewWriteAcceptOwnership(c gobindings.BurnMintERC677Interface) *cld_ops.Operation[contract.FunctionInput[struct{}], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[struct{}, gobindings.BurnMintERC677Interface]{
		Name:         "burn-mint-erc677:accept-ownership",
		Version:      Version,
		Description:  "Calls acceptOwnership on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.BurnMintERC677MetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.BurnMintERC677Interface, opts *bind.CallOpts, caller common.Address, args struct{}) (bool, error) {
			return false, nil
		},
		CallContract: func(
			c gobindings.BurnMintERC677Interface,
			opts *bind.TransactOpts,
			args struct{},
		) (*types.Transaction, error) {
			return c.AcceptOwnership(opts)
		},
	})
}
