// Code generated by operations-gen. DO NOT EDIT.

package many_chain_multi_sig

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	gobindings "github.com/smartcontractkit/ccip-owner-contracts/pkg/gethwrappers"
	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
	zkbindings "github.com/smartcontractkit/mcms/sdk/zksync/bindings"
)

var ContractType cldf_deployment.ContractType = "ManyChainMultiSig"
var Version = semver.MustParse("1.0.0")
var ProposerManyChainMultiSigContractType cldf_deployment.ContractType = "ProposerManyChainMultiSig"
var ProposerManyChainMultiSigTypeAndVersion = cldf_deployment.NewTypeAndVersion(ProposerManyChainMultiSigContractType, *Version)
var BypasserManyChainMultiSigContractType cldf_deployment.ContractType = "BypasserManyChainMultiSig"
var BypasserManyChainMultiSigTypeAndVersion = cldf_deployment.NewTypeAndVersion(BypasserManyChainMultiSigContractType, *Version)
var CancellerManyChainMultiSigContractType cldf_deployment.ContractType = "CancellerManyChainMultiSig"
var CancellerManyChainMultiSigTypeAndVersion = cldf_deployment.NewTypeAndVersion(CancellerManyChainMultiSigContractType, *Version)

type SetConfigArgs struct {
	SignerAddresses []common.Address `json:"signerAddresses"`
	SignerGroups    []uint8          `json:"signerGroups"`
	GroupQuorums    [32]uint8        `json:"groupQuorums"`
	GroupParents    [32]uint8        `json:"groupParents"`
	ClearRoot       bool             `json:"clearRoot"`
}

type ConstructorArgs = struct{}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "many-chain-multi-sig:deploy",
	Version:          Version,
	Description:      "Deploys the ManyChainMultiSig contract",
	ContractMetadata: gobindings.ManyChainMultiSigMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		ProposerManyChainMultiSigTypeAndVersion.String(): {
			EVM:      common.FromHex(gobindings.ManyChainMultiSigMetaData.Bin),
			ZkSyncVM: zkbindings.ManyChainMultiSigZkBytecode,
		},
		BypasserManyChainMultiSigTypeAndVersion.String(): {
			EVM:      common.FromHex(gobindings.ManyChainMultiSigMetaData.Bin),
			ZkSyncVM: zkbindings.ManyChainMultiSigZkBytecode,
		},
		CancellerManyChainMultiSigTypeAndVersion.String(): {
			EVM:      common.FromHex(gobindings.ManyChainMultiSigMetaData.Bin),
			ZkSyncVM: zkbindings.ManyChainMultiSigZkBytecode,
		},
	},
})

func NewWriteSetConfig(c gobindings.ManyChainMultiSigInterface) *cld_ops.Operation[contract.FunctionInput[SetConfigArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[SetConfigArgs, gobindings.ManyChainMultiSigInterface]{
		Name:         "many-chain-multi-sig:set-config",
		Version:      Version,
		Description:  "Calls setConfig on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.ManyChainMultiSigMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.ManyChainMultiSigInterface, opts *bind.CallOpts, caller common.Address, args SetConfigArgs) (bool, error) {
			return contract.OnlyOwner(c, opts, caller, args)
		},
		CallContract: func(
			c gobindings.ManyChainMultiSigInterface,
			opts *bind.TransactOpts,
			args SetConfigArgs,
		) (*types.Transaction, error) {
			return c.SetConfig(opts, args.SignerAddresses, args.SignerGroups, args.GroupQuorums, args.GroupParents, args.ClearRoot)
		},
	})
}
