// Code generated by operations-gen. DO NOT EDIT.

package many_chain_multi_sig

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/common"
	gobindings "github.com/smartcontractkit/ccip-owner-contracts/gethwrappers"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	zkbindings "github.com/smartcontractkit/mcms/sdk/zksync/bindings"
)

var ContractType cldf_deployment.ContractType = "ManyChainMultiSig"
var Version = semver.MustParse("1.0.0")
var ProposerManyChainMultiSigContractType cldf_deployment.ContractType = "ProposerManyChainMultiSig"
var ProposerManyChainMultiSigTypeAndVersion = cldf_deployment.NewTypeAndVersion(ProposerManyChainMultiSigContractType, *Version)
var BypasserManyChainMultiSigContractType cldf_deployment.ContractType = "BypasserManyChainMultiSig"
var BypasserManyChainMultiSigTypeAndVersion = cldf_deployment.NewTypeAndVersion(BypasserManyChainMultiSigContractType, *Version)
var CancellerManyChainMultiSigContractType cldf_deployment.ContractType = "CancellerManyChainMultiSig"
var CancellerManyChainMultiSigTypeAndVersion = cldf_deployment.NewTypeAndVersion(CancellerManyChainMultiSigContractType, *Version)

type ConstructorArgs = struct{}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "many-chain-multi-sig:deploy",
	Version:          Version,
	Description:      "Deploys the ManyChainMultiSig contract",
	ContractMetadata: gobindings.ManyChainMultiSigMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		ProposerManyChainMultiSigTypeAndVersion.String(): {
			EVM:      common.FromHex(gobindings.ManyChainMultiSigMetaData.Bin),
			ZkSyncVM: zkbindings.ManyChainMultiSigZkBytecode,
		},
		BypasserManyChainMultiSigTypeAndVersion.String(): {
			EVM:      common.FromHex(gobindings.ManyChainMultiSigMetaData.Bin),
			ZkSyncVM: zkbindings.ManyChainMultiSigZkBytecode,
		},
		CancellerManyChainMultiSigTypeAndVersion.String(): {
			EVM:      common.FromHex(gobindings.ManyChainMultiSigMetaData.Bin),
			ZkSyncVM: zkbindings.ManyChainMultiSigZkBytecode,
		},
	},
})
