package evmdeploytopology

import (
	"math/big"

	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/common"
	bindings "github.com/smartcontractkit/ccip-owner-contracts/pkg/gethwrappers"
	mcmscontracts "github.com/smartcontractkit/chainlink-deployments-framework/engine/cld/contracts/mcms"
	zkbindings "github.com/smartcontractkit/mcms/sdk/zksync/bindings"

	"github.com/smartcontractkit/cld-changesets/internal/semvers"
	"github.com/smartcontractkit/cld-changesets/mcms/evm/operations"
)

type OpDeployTimelockInput struct {
	TimelockMinDelay *big.Int         `json:"timelockMinDelay"`
	Admin            common.Address   `json:"admin"`      // Admin of the timelock contract, usually the deployer key
	Proposers        []common.Address `json:"proposers"`  // Proposer of the timelock contract, usually the deployer key
	Executors        []common.Address `json:"executors"`  // Executor of the timelock contract, usually the call proxy
	Cancellers       []common.Address `json:"cancellers"` // Canceller of the timelock contract, usually the deployer key
	Bypassers        []common.Address `json:"bypassers"`  // Bypasser of the timelock contract, usually the deployer key
}

// TODO: This deploy operation is a candidate for being autogenerated by the
// operations-gen CLI tool. Once that tool supports EVM contract deployments,
// we may be able to remove this handwritten operation entirely.
var OpDeployTimelock = operations.NewEVMDeployOperation(
	"evm-timelock-deploy",
	semver.MustParse("1.0.0"),
	"Deploys Timelock contract on the specified EVM chains",
	mcmscontracts.RBACTimelock,
	bindings.RBACTimelockMetaData,
	&operations.ContractOpts{
		Version:          &semvers.V1_0_0,
		EVMBytecode:      common.FromHex(bindings.RBACTimelockBin),
		ZkSyncVMBytecode: zkbindings.RBACTimelockZkBytecode,
	},
	func(input OpDeployTimelockInput) []any {
		return []any{
			input.TimelockMinDelay,
			input.Admin,
			input.Proposers,
			input.Executors,
			input.Cancellers,
			input.Bypassers,
		}
	},
)

type OpEVMDeployMCMOutput struct {
	Address common.Address `json:"address"`
}

// TODO: All MCM deploy operations below are good candidates for being
// autogenerated by the operations-gen CLI tool. Once that tool supports
// EVM contract deployments, we may be able to remove these handwritten
// operations entirely.

var OpDeployProposerMCM = operations.NewEVMDeployOperation(
	"evm-proposer-mcm-deploy",
	semver.MustParse("1.0.0"),
	"Deploys Proposer MCM contract",
	mcmscontracts.ProposerManyChainMultisig,
	bindings.ManyChainMultiSigMetaData,
	&operations.ContractOpts{
		Version:          &semvers.V1_0_0,
		EVMBytecode:      common.FromHex(bindings.ManyChainMultiSigBin),
		ZkSyncVMBytecode: zkbindings.ManyChainMultiSigZkBytecode,
	},
	func(input any) []any {
		return []any{}
	},
)

var OpDeployBypasserMCM = operations.NewEVMDeployOperation(
	"evm-bypasser-mcm-deploy",
	semver.MustParse("1.0.0"),
	"Deploys Bypasser MCM contract",
	mcmscontracts.BypasserManyChainMultisig,
	bindings.ManyChainMultiSigMetaData,
	&operations.ContractOpts{
		Version:          &semvers.V1_0_0,
		EVMBytecode:      common.FromHex(bindings.ManyChainMultiSigBin),
		ZkSyncVMBytecode: zkbindings.ManyChainMultiSigZkBytecode,
	},
	func(input any) []any {
		return []any{}
	},
)

var OpDeployCancellerMCM = operations.NewEVMDeployOperation(
	"evm-canceller-mcm-deploy",
	semver.MustParse("1.0.0"),
	"Deploys Canceller MCM contract",
	mcmscontracts.CancellerManyChainMultisig,
	bindings.ManyChainMultiSigMetaData,
	&operations.ContractOpts{
		Version:          &semvers.V1_0_0,
		EVMBytecode:      common.FromHex(bindings.ManyChainMultiSigBin),
		ZkSyncVMBytecode: zkbindings.ManyChainMultiSigZkBytecode,
	},
	func(input any) []any {
		return []any{}
	},
)

type OpDeployCallProxyInput struct {
	Timelock common.Address `json:"timelock"`
}

// TODO: This deploy operation is a candidate for being autogenerated by the
// operations-gen CLI tool. Once that tool supports EVM contract deployments,
// we may be able to remove this handwritten operation entirely.
var OpDeployCallProxy = operations.NewEVMDeployOperation(
	"evm-call-proxy-deploy",
	semver.MustParse("1.0.0"),
	"Deploys CallProxy contract on the specified EVM chains",
	mcmscontracts.CallProxy,
	bindings.CallProxyMetaData,
	&operations.ContractOpts{
		Version:          &semvers.V1_0_0,
		EVMBytecode:      common.FromHex(bindings.CallProxyBin),
		ZkSyncVMBytecode: zkbindings.CallProxyZkBytecode,
	},
	func(input OpDeployCallProxyInput) []any {
		return []any{
			input.Timelock,
		}
	},
)
