// Code generated by operations-gen. DO NOT EDIT.

package rbac_timelock

import (
	"math/big"

	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"

	gobindings "github.com/smartcontractkit/ccip-owner-contracts/pkg/gethwrappers"
	cldf_evm "github.com/smartcontractkit/chainlink-deployments-framework/chain/evm"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	cld_ops "github.com/smartcontractkit/chainlink-deployments-framework/operations"
	zkbindings "github.com/smartcontractkit/mcms/sdk/zksync/bindings"
)

var ContractType cldf_deployment.ContractType = "RBACTimelock"
var Version = semver.MustParse("1.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type GrantRoleArgs struct {
	Role    [32]byte       `json:"role"`
	Account common.Address `json:"account"`
}

type ConstructorArgs struct {
	MinDelay   *big.Int         `json:"minDelay"`
	Admin      common.Address   `json:"admin"`
	Proposers  []common.Address `json:"proposers"`
	Executors  []common.Address `json:"executors"`
	Cancellers []common.Address `json:"cancellers"`
	Bypassers  []common.Address `json:"bypassers"`
}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "rbac-timelock:deploy",
	Version:          Version,
	Description:      "Deploys the RBACTimelock contract",
	ContractMetadata: gobindings.RBACTimelockMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		cldf_deployment.NewTypeAndVersion(ContractType, *Version).String(): {
			EVM:      common.FromHex(gobindings.RBACTimelockMetaData.Bin),
			ZkSyncVM: zkbindings.RBACTimelockZkBytecode,
		},
	},
})

func NewWriteGrantRole(c gobindings.RBACTimelockInterface) *cld_ops.Operation[contract.FunctionInput[GrantRoleArgs], contract.WriteOutput, cldf_evm.Chain] {
	return contract.NewWrite(contract.WriteParams[GrantRoleArgs, gobindings.RBACTimelockInterface]{
		Name:         "rbac-timelock:grant-role",
		Version:      Version,
		Description:  "Calls grantRole on the contract",
		ContractType: ContractType,
		ContractABI:  gobindings.RBACTimelockMetaData.ABI,
		Contract:     c,
		IsAllowedCaller: func(c gobindings.RBACTimelockInterface, opts *bind.CallOpts, caller common.Address, args GrantRoleArgs) (bool, error) {
			return contract.HasRole(c, opts, [32]byte{0xa4, 0x98, 0x07, 0x20, 0x5c, 0xe4, 0xd3, 0x55, 0x09, 0x2e, 0xf5, 0xa8, 0xa1, 0x8f, 0x56, 0xe8, 0x91, 0x3c, 0xf4, 0xa2, 0x01, 0xfb, 0xe2, 0x87, 0x82, 0x5b, 0x09, 0x56, 0x93, 0xc2, 0x17, 0x75}, caller)
		},
		CallContract: func(
			c gobindings.RBACTimelockInterface,
			opts *bind.TransactOpts,
			args GrantRoleArgs,
		) (*types.Transaction, error) {
			return c.GrantRole(opts, args.Role, args.Account)
		},
	})
}
