version: "1.0.0"
chain_family: evm

output:
  base_path: "."

contracts:
  - contract_name: BurnMintERC677
    version: "1.0.0"
    package_name: burn_mint_erc677
    gobindings_package: "github.com/smartcontractkit/chainlink-evm/gethwrappers/shared/generated/initial/burn_mint_erc677"
    omit_deploy: true
    functions:
      - name: owner
        access: public
      - name: transferOwnership
        access: owner
      - name: acceptOwnership
        access: private
