// Code generated by operations-gen. DO NOT EDIT.

package call_proxy

import (
	"github.com/Masterminds/semver/v3"
	"github.com/ethereum/go-ethereum/common"
	gobindings "github.com/smartcontractkit/ccip-owner-contracts/gethwrappers"
	"github.com/smartcontractkit/chainlink-deployments-framework/chain/evm/operations2/contract"
	cldf_deployment "github.com/smartcontractkit/chainlink-deployments-framework/deployment"
	zkbindings "github.com/smartcontractkit/mcms/sdk/zksync/bindings"
)

var ContractType cldf_deployment.ContractType = "CallProxy"
var Version = semver.MustParse("1.0.0")
var TypeAndVersion = cldf_deployment.NewTypeAndVersion(ContractType, *Version)

type ConstructorArgs struct {
	Target common.Address `json:"target"`
}

var Deploy = contract.NewDeploy(contract.DeployParams[ConstructorArgs]{
	Name:             "call-proxy:deploy",
	Version:          Version,
	Description:      "Deploys the CallProxy contract",
	ContractMetadata: gobindings.CallProxyMetaData,
	BytecodeByTypeAndVersion: map[string]contract.Bytecode{
		cldf_deployment.NewTypeAndVersion(ContractType, *Version).String(): {
			EVM:      common.FromHex(gobindings.CallProxyMetaData.Bin),
			ZkSyncVM: zkbindings.CallProxyZkBytecode,
		},
	},
})
