version: "1.0.0"
chain_family: evm

output:
  base_path: "."

input:
  zksync_bindings_package: "github.com/smartcontractkit/mcms/sdk/zksync/bindings"

contracts:
  - contract_name: ManyChainMultiSig
    version: "1.0.0"
    package_name: many_chain_multi_sig
    gobindings_package: "github.com/smartcontractkit/ccip-owner-contracts/gethwrappers"
    zksync_bytecode: ManyChainMultiSigZkBytecode
    deploy_contract_types:
      - ProposerManyChainMultiSig
      - BypasserManyChainMultiSig
      - CancellerManyChainMultiSig
    functions: []

  - contract_name: RBACTimelock
    version: "1.0.0"
    package_name: rbac_timelock
    gobindings_package: "github.com/smartcontractkit/ccip-owner-contracts/gethwrappers"
    zksync_bytecode: RBACTimelockZkBytecode
    functions:
      - name: grantRole
        access: role
        role: ADMIN_ROLE

  - contract_name: CallProxy
    version: "1.0.0"
    package_name: call_proxy
    gobindings_package: "github.com/smartcontractkit/ccip-owner-contracts/gethwrappers"
    zksync_bytecode: CallProxyZkBytecode
    functions: []
